### ISSUE TITLE
style.css does not override

### ISSUE THREAD

**Issue by felix-berlin** [webdevsuperfast/bootstrap-for-genesis#1]
The main style.css does not override the bootstrap css.
When i type h1, h2 { font-family: arial, sans-serif;} the font does not change.
Only body h1, body h2 { font-family: arial, sans-serif;} overrides the bootstrap css.
![error](https://user-images.githubusercontent.com/17964384/35099266-9f5fc8c8-fc57-11e7-993a-de03cf17bce1.JPG)

**Comment by webdevsuperfast** [comment]
@felix-berlin please put your changes on `assets/css/app.css` or via `Appearance > Customize > Additional CSS`. You can also customize it by utilizing the build tool available(gulp).
