### ISSUE TITLE
Wrong theme name for load_child_theme_textdomain

### ISSUE THREAD

**Issue by felix-berlin** [webdevsuperfast/bootstrap-for-genesis#13]
You have to put the parent theme name in to load_child_theme_textdomain.
Like this:

`    // Load Child theme text domain
    load_child_theme_textdomain('genesis', get_stylesheet_directory() . '/languages');`

Otherwise it wont work.

**Comment by webdevsuperfast** [comment]
@felix-berlin the implementation is correct based on `https://codex.wordpress.org/Child_Themes#Internationalization`. You don't need to put the parent theme name.
