### ISSUE TITLE
Conflict sorce map with autoprefixer

### ISSUE THREAD

**Issue by ProjectKarol** [webdevsuperfast/bootstrap-for-genesis#14]
I Had problem with source map ,  isn't  show path of files.  
It appears that was conflict witch latest autoprefixer plugin. 
I still don't find solution

**Comment by webdevsuperfast** [comment]
@ProjectKarol I'm using WPGulp, you can check [this](https://github.com/ahmadawais/WPGulp/issues/130) issue regarding it.
