### ISSUE TITLE
Cant wp_dequeue_script

### ISSUE THREAD

**Issue by felix-berlin** [webdevsuperfast/bootstrap-for-genesis#15]
I used the following code to dequeue some scripts on custom posttypes. But dequeue dont work in the scripts.php 

`if ( is_singular( 'portfolio' ) ) {
	wp_dequeue_script( 'owl-carousel' );
	wp_dequeue_script( 'vivus' );

}`

You know why?

**Comment by felix-berlin** [comment]
I also used the example from wp codex

`/**
 * Dequeue the jQuery UI script.
 *
 * Hooked to the wp_print_scripts action, with a late priority (100),
 * so that it is after the script was enqueued.
 */
function wpdocs_dequeue_script() {
   wp_dequeue_script( 'jquery-ui-core' );
}
add_action( 'wp_print_scripts', 'wpdocs_dequeue_script', 100 );`

https://codex.wordpress.org/Function_Reference/wp_dequeue_script

**Comment by webdevsuperfast** [comment]
@felix-berlin are you dequeueing the scripts used on plugins? The scripts you're referring is not present on the theme.

**Comment by webdevsuperfast** [comment]
@felix-berlin instead of dequeueing you should try enqueuing your scripts on specific post type. That way your scripts will just load based on your own condition.

**Comment by webdevsuperfast** [comment]
@felix-berlin glad that works for you :)
