### ISSUE TITLE
BrowserSync Hanging

### ISSUE THREAD

**Issue by jmester13** [webdevsuperfast/bootstrap-for-genesis#16]
Hello, 

I'm excited to use this theme but am struggling with BrowserSync. It keeps hanging with 2-4 buffered events... I haven't changed anything I'm just trying to run this right out of the box, following the install instructions. 

Additionally how would you change the localhost port from 3000 to 8888? I'm on MacOS Mojave, using VS Code and Chrome. 

I have tried this, 

function browserSyncServe(done) {
    browserSync.init({
        injectChanges: true,
        proxy: 'http://localhost:8888/wordpress/'
    })
    done();
}

But that doesn't work. 

Thanks

**Comment by felix-berlin** [comment]
I'm still working with the version where WPGulp is included. Works fine for me. Maybe you try this.
https://github.com/webdevsuperfast/bootstrap-for-genesis/tree/ab89546ebbea4e7977f3979ee892fbedd530cb15

**Comment by webdevsuperfast** [comment]
@jmester13 Issue with CSS not compiling is fixed. With regards to changing Browser Sync port number please refer to their documentation [here](https://browsersync.io/docs/options). Will close this for now, feel free to open an issue anytime :).
