### ISSUE TITLE
Why jquery slim ?

### ISSUE THREAD

**Issue by ctoveloz** [webdevsuperfast/bootstrap-for-genesis#18]
I spent a good deal of time figuring out various scripting errors in plugins until I realized that the problem was something of the theme, but specifically Jquery Slim. Why not use the Jquery default version?

**Comment by webdevsuperfast** [comment]
@ctoveloz I just followed Bootstrap's [official documentation](https://getbootstrap.com/docs/4.3/getting-started/introduction/) and used jQuery slim. You can however changed it to whatever you wanted.
