### ISSUE TITLE
Option to switch from fluid-container to container in the admin

### ISSUE THREAD

**Issue by vynnus** [webdevsuperfast/bootstrap-for-genesis#19]
I'd like to suggest this option to switch the theme (from inside the admin) between a container ou fluid-container.

Or if I can do it by a snippet just let me know.

 Thanks

**Comment by vynnus** [comment]
just made with a snippet:

`add_filter( 'genesis_attr_site-container', 'themeprefix_site_container_class' );
function themeprefix_site_container_class( $attributes ) { 
 $attributes['class'] = 'container';
 return $attributes;
}`

**Comment by webdevsuperfast** [comment]
@vynnus Awesome suggestion, will certainly look into it and add the option in the future. Meanwhile, adding filter to `site-container` attributes works like what you did. Thanks!

**Comment by webdevsuperfast** [comment]
@vynnus Added customizer setting in switching between `container` and `container-fluid` as documented on [Bootstrap](https://getbootstrap.com/docs/4.3/layout/overview/).
