### ISSUE TITLE
Remove Fontawesome

### ISSUE THREAD

**Issue by felix-berlin** [webdevsuperfast/bootstrap-for-genesis#2]
Hi, i would like to remove the fontawesome files from my project.
I removed it from the style.scss file but it is still present. I also looked for it in scripts.php.
I am grateful for any help.

![fontawesome](https://user-images.githubusercontent.com/17964384/35578197-a72083fa-05e3-11e8-8e9f-3392b0e7058c.JPG)

**Comment by webdevsuperfast** [comment]
If you remove it on the style.scss file then it shouldn't be called anymore, to remove fontawesome completely on your theme you will need to remove the following:

1. gulpfile.js:

`// Copy bootstrap fonts to assets folder
gulp.task('copy', function() {
    return gulp.src(['node_modules/font-awesome/fonts/**/**'], {
        base: 'node_modules/font-awesome/fonts'
    })
    .pipe(gulp.dest('assets/fonts/fontawesome'));
});`

Remove the copy task here:
`// Default task
gulp.task('default', function() {
    // gulp.start('styles', 'lint', 'scripts', 'watch');
    runSequence(
        'clean',
        ['copy', 'styles', 'lint', 'scripts'],
        'watch'
    );
});`

2. Remove the fonts folder from assets folder.

3. Remove fontawesome from package.json:
`"font-awesome": "FortAwesome/Font-Awesome#^4.7.0",`

That's it, please ensure you don't have any plugins that is calling fontawesome.

Thanks!

**Comment by felix-berlin** [comment]
Thanks for the quick answer!

I have found the solution, the Kirki Toolkit adds fontawesome.

**Comment by webdevsuperfast** [comment]
Awesome @felix-berlin glad you found the solution.
