### ISSUE TITLE
Imcompatibility with WPForo plugin

### ISSUE THREAD

**Issue by vynnus** [webdevsuperfast/bootstrap-for-genesis#24]
@webdevsuperfast I started using WPForo plugin here:
https://entreganobrasil.com.br/forum/

But I found your theme has an issue with it.
Please create a user and post a test topic.
Then try to edit it. You'll see the editor comes empty.
It seems it something related to Tine MCE.
Also, check the error showed in the Inspect of Chrome.

Well, the error is related to the theme.
I switched to another theme and it's working fine.

Would you mind give me the solution for this?

**Comment by webdevsuperfast** [comment]
@vynnus thanks for reporting the issue. Will look into the plugin and see what's the issue with it. :)

**Comment by webdevsuperfast** [comment]
@vynnus the issue might be due to the `jQuery` used in the theme, what you can do is comment line `23` to `26` on `lib/scripts.php` and use the built-in jQuery that comes with WP.

**Comment by vynnus** [comment]
@webdevsuperfast just did that.
jquery seems to being loaded only from the theme.
After I comment those lines you mentioned forum and other plugins stopped to work.

then I pasted this code into the functions.php and it worked.

Thanks for the quick support!

`function theme_scripts() {
  wp_enqueue_script('jquery');
}
add_action('wp_enqueue_scripts', 'theme_scripts');`
