### ISSUE TITLE
Is it still active development?

### ISSUE THREAD

**Issue by weartstudio** [webdevsuperfast/bootstrap-for-genesis#27]
Hello, 

this starter theme is still in active devlopment?

**Comment by webdevsuperfast** [comment]
@weartstudio 

Currently it's not under active development but I might resume development possibly next year to incorporate the latest features from Genesis including the ones listed in my `Todos` list and Bootstrap 5.

Thanks :)

**Comment by weartstudio** [comment]
Thank you, I will be waiting for that :)
