### ISSUE TITLE
Genesis Theme not apply properly

### ISSUE THREAD

**Issue by setevejhone** [webdevsuperfast/bootstrap-for-genesis#28]
i recently switch my [website ](https://www.miscof.com/)theme from astra to genesis eleven Pro.but some of pages of my website still show in astra theme don't know what the issue is.

**Comment by webdevsuperfast** [comment]
@setevejhone

You may want to direct your issue with the developer of Genesis Eleven Pro. Upon checking your website, it seems you're using a caching plugin, you could try purging your cache and check if it helps.

Thanks!
