### ISSUE TITLE
How to pull menu items right in main navigation?

### ISSUE THREAD

**Issue by sebgates** [webdevsuperfast/bootstrap-for-genesis#3]
Hi. I am trying to pull menu items on the theme to the right and leave the .navbar-brand on the left. Do you have a solution? I have tried adding css from Bootstrap with no luck.

**Comment by webdevsuperfast** [comment]
@sebgates Thanks for the interest. Replace `navbar-nav mr-auto` to `navbar-nav ml-auto` on line 30 in `lib/nav.php` this will push the navbar to the right as explained on [StackOverflow](https://stackoverflow.com/questions/40178386/bootstrap-4-navbar-items-on-right-side).

**Comment by sebgates** [comment]
Thanks

**Comment by webdevsuperfast** [comment]
You're welcome :bowing_man:
