### ISSUE TITLE
Issue with remote smartmenu repo and npm install

### ISSUE THREAD

**Issue by christooma** [webdevsuperfast/bootstrap-for-genesis#6]
Couldn't get npm install to work, was always getting an error related to **usr/bin/git checkout 1.1.0.**  Turns out the remote repo for smartmenus is the culprit.  Removing that and manually installing smartmenus with npm fixed it - allowing me to npm install all dependencies for this theme.

**Comment by webdevsuperfast** [comment]
@christooma I'm using Yarn to install dependencies and have not had any issues installing dependencies. Haven't tried installed using `npm install`.
