### ISSUE TITLE
Replacing Jquery Slim with Jquery

### ISSUE THREAD

**Issue by broskees** [webdevsuperfast/bootstrap-for-genesis#7]
I inherited this a built version of this theme, I'm trying to replace jquery-slim with jquery so I can add some functionality. How can I do that?

**Comment by webdevsuperfast** [comment]
Hi @broskees, If you're using Yarn you can change line 55 in `gulpfile.js` to `node_modules/jquery/dist/jquery.js` and line 26 in `scripts.php` to `wp_register_script( 'jquery', BFG_THEME_JS . 'jquery.min.js', array(), $version, true );`. You can also use the CDN version, just replace line 26 to `wp_register_script( 'jquery', 'https://code.jquery.com/jquery-3.3.1.min.js', array(), $version, true );`. Let me know if that helps.

**Comment by broskees** [comment]
Thanks!
