### ISSUE TITLE
JS errors.

### ISSUE THREAD

**Issue by idpokute** [webdevsuperfast/bootstrap-for-genesis#9]
I noticed that hamburger button doesn't work on the site. I guess following two errors are related.
FYI. when I use CDN for popper, it didn't show the error.

popper.min.js?ver=2.0.2:1 Uncaught TypeError: Cannot set property 'Popper' of undefined
    at popper.min.js?ver=2.0.2:1
    at popper.min.js?ver=2.0.2:1
(anonymous) @ popper.min.js?ver=2.0.2:1
(anonymous) @ popper.min.js?ver=2.0.2:1
bootstrap.min.js?ver=2.0.2:1 Uncaught TypeError: Cannot set property 'bootstrap' of undefined
    at bootstrap.min.js?ver=2.0.2:1
    at bootstrap.min.js?ver=2.0.2:1

**Comment by idpokute** [comment]
I just fixed this issue. I will send PR  tomorrow.

**Comment by webdevsuperfast** [comment]
@idpokute I'll looked into it, have been busy as of late. Send a pull request and will check it.

**Comment by webdevsuperfast** [comment]
@idpokute pull request merged. Closing this for now. Thanks!
